name: Deploy to GitHub Pages

on:
  push:
    branches: [deploy]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm ci
      - name: Build
        env:
          VITE_REACT_APP_API_URL : ${{ secrets.VITE_REACT_APP_API_URL }}
          VITE_REACT_APP_CLOUD_NAME: ${{ secrets.VITE_REACT_APP_CLOUD_NAME }}
          VITE_REACT_APP_UPLOAD_PRESET :  ${{ secrets.VITE_REACT_APP_UPLOAD_PRESET }}
        run: |
          npm run build
          cp -r build/* docs/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs